#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonAppliWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bddEQL")]
	public partial class BddClientDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Définitions de méthodes d'extensibilité
    partial void OnCreated();
    partial void InsertTelephoneSet(TelephoneSet instance);
    partial void UpdateTelephoneSet(TelephoneSet instance);
    partial void DeleteTelephoneSet(TelephoneSet instance);
    partial void Insertclientbdd(clientbdd instance);
    partial void Updateclientbdd(clientbdd instance);
    partial void Deleteclientbdd(clientbdd instance);
    #endregion
		
		public BddClientDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bddEQLConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BddClientDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BddClientDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BddClientDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BddClientDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<clientregion> clientregion
		{
			get
			{
				return this.GetTable<clientregion>();
			}
		}
		
		public System.Data.Linq.Table<TelephoneSet> TelephoneSet
		{
			get
			{
				return this.GetTable<TelephoneSet>();
			}
		}
		
		public System.Data.Linq.Table<clientbdd> clientbdd
		{
			get
			{
				return this.GetTable<clientbdd>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientregion")]
	public partial class clientregion
	{
		
		private int _noclient;
		
		private string _nom;
		
		private string _adresse;
		
		private string _nomregion;
		
		public clientregion()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noclient", DbType="Int NOT NULL")]
		public int noclient
		{
			get
			{
				return this._noclient;
			}
			set
			{
				if ((this._noclient != value))
				{
					this._noclient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this._nom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(50)")]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this._adresse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomregion", DbType="NVarChar(50)")]
		public string nomregion
		{
			get
			{
				return this._nomregion;
			}
			set
			{
				if ((this._nomregion != value))
				{
					this._nomregion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TelephoneSet")]
	public partial class TelephoneSet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTelephone;
		
		private string _NumeroTel;
		
		private string _TypeNumero;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTelephoneChanging(int value);
    partial void OnIdTelephoneChanged();
    partial void OnNumeroTelChanging(string value);
    partial void OnNumeroTelChanged();
    partial void OnTypeNumeroChanging(string value);
    partial void OnTypeNumeroChanged();
    #endregion
		
		public TelephoneSet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTelephone", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdTelephone
		{
			get
			{
				return this._IdTelephone;
			}
			set
			{
				if ((this._IdTelephone != value))
				{
					this.OnIdTelephoneChanging(value);
					this.SendPropertyChanging();
					this._IdTelephone = value;
					this.SendPropertyChanged("IdTelephone");
					this.OnIdTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumeroTel", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NumeroTel
		{
			get
			{
				return this._NumeroTel;
			}
			set
			{
				if ((this._NumeroTel != value))
				{
					this.OnNumeroTelChanging(value);
					this.SendPropertyChanging();
					this._NumeroTel = value;
					this.SendPropertyChanged("NumeroTel");
					this.OnNumeroTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeNumero", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TypeNumero
		{
			get
			{
				return this._TypeNumero;
			}
			set
			{
				if ((this._TypeNumero != value))
				{
					this.OnTypeNumeroChanging(value);
					this.SendPropertyChanging();
					this._TypeNumero = value;
					this.SendPropertyChanged("TypeNumero");
					this.OnTypeNumeroChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.client")]
	public partial class clientbdd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _noclient;
		
		private string _nom;
		
		private string _adresse;
		
		private System.Nullable<int> _noregion;
		
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnoclientChanging(int value);
    partial void OnnoclientChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnadresseChanging(string value);
    partial void OnadresseChanged();
    partial void OnnoregionChanging(System.Nullable<int> value);
    partial void OnnoregionChanged();
    #endregion
		
		public clientbdd()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noclient", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int noclient
		{
			get
			{
				return this._noclient;
			}
			set
			{
				if ((this._noclient != value))
				{
					this.OnnoclientChanging(value);
					this.SendPropertyChanging();
					this._noclient = value;
					this.SendPropertyChanged("noclient");
					this.OnnoclientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="NVarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adresse", DbType="NVarChar(50)")]
		public string adresse
		{
			get
			{
				return this._adresse;
			}
			set
			{
				if ((this._adresse != value))
				{
					this.OnadresseChanging(value);
					this.SendPropertyChanging();
					this._adresse = value;
					this.SendPropertyChanged("adresse");
					this.OnadresseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noregion", DbType="Int")]
		public System.Nullable<int> noregion
		{
			get
			{
				return this._noregion;
			}
			set
			{
				if ((this._noregion != value))
				{
					this.OnnoregionChanging(value);
					this.SendPropertyChanging();
					this._noregion = value;
					this.SendPropertyChanged("noregion");
					this.OnnoregionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
