//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManipulationEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class bddEQLEntities : DbContext
    {
        public bddEQLEntities()
            : base("name=bddEQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<Telephone> TelephoneSet { get; set; }
    
        public virtual ObjectResult<GetClientAndRegion_Result> GetClientAndRegion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClientAndRegion_Result>("GetClientAndRegion");
        }
    }
}
